### ISSUE TITLE
Relicense under dual MIT/Apache-2.0

### ISSUE THREAD

**Issue by Qwaz** [PLUS-POSTECH/Owl#13]
이유와 예시:
https://github.com/sfackler/rust-postgres-macros/issues/19

**Comment by KSAlpha** [comment]
92aec2f 에 반영되었습니다.

**Comment by Qwaz** [comment]
LICENSE 파일 두 개로 분리해주세요

**Comment by KSAlpha** [comment]
efb76f2 에 반영되었습니다.
