### ISSUE TITLE
Path (attachment name) injection

### ISSUE THREAD

**Issue by KSAlpha** [PLUS-POSTECH/Owl#33]
Attachment name can include special path such as `..` or `/xxx` which can result in path injection.

**Comment by Qwaz** [comment]
이거 이외에도 같은 폴더에 `ex.py` 있을 때 `./ex.py`로 등록하지 않으면 리눅스에서 실행되지 않는 문제도 있습니다. 경로 빼고 폴더명만 전송하도록 변경한 뒤, 리눅스에서는 실행 커맨드 만들 때 앞에 `./` 붙이도록 정규화하면 될 것 같습니다.
