### ISSUE TITLE
RPC Interface (owl-cli and owl-daemon)

### ISSUE THREAD

**Issue by KSAlpha** [PLUS-POSTECH/Owl#7]

**Comment by Qwaz** [comment]
Cap'n Proto Rust 바인딩이 생각보다 안 예쁘네요. 이런거 쓰는것도 고려해봐도 좋을 것 같아요.
https://github.com/google/tarpc

**Comment by KSAlpha** [comment]
단점은 이걸 사용하게 되면 wasm이나 rocket같은 녀석을 쓰지 않는 이상 웹(김칫국) 형태의 프론트엔드를 만들기 어렵다는 점...

**Comment by KSAlpha** [comment]
Merged #18
